# Custom values for nginx application
# This overrides the official nginx chart values

# Use official nginx chart
nginx:
  # Basic configuration
  replicaCount: 2
  
  # Image settings
  image:
    registry: docker.io
    repository: bitnami/nginx
    tag: "1.25"
  
  # Container configuration - fix the port mapping
  containerPorts:
    http: 80
  
  # Service configuration - NodePort for external access
  service:
    type: NodePort
    port: 80
    targetPort: 
      http: 80
      https: 443
    nodePort: 30080  # Specific NodePort for easy access
  
  # Resource limits
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  
  # Disable features we don't need
  ingress:
    enabled: false
  
  # Security settings
  containerSecurityContext:
    enabled: false
  
  podSecurityContext:
    enabled: false
