# Custom values for nginx application
# This demonstrates GitOps upgrades and rollbacks with visual changes

# Use official nginx chart
nginx:
  # Basic configuration
  replicaCount: 2
  
  # Deployment strategy
  deployment:
    revisionHistoryLimit: 3  # Keep only last 3 ReplicaSets
  
  # Image settings
  image:
    registry: docker.io
    repository: bitnami/nginx
    tag: "1.29.1"
  
  # Container configuration - use non-privileged port
  containerPorts:
    http: 8080  # Changed from 80 to avoid privileged port issues
  
  # Color scheme selector - change this to switch themes quickly!
  colorScheme: "blue"  # Options: "blue", "green", "purple", "orange"
  
  # Service configuration - NodePort with specific port for reliable access
  service:
    type: NodePort
    ports:
      http: 80
    targetPort:
      http: http
    nodePorts:
      http: "30080"  # Specific NodePort for easy access
  
  # Resource limits
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  
  # Disable features we don't need
  ingress:
    enabled: false
  
  # Security settings
  containerSecurityContext:
    enabled: false
  
  podSecurityContext:
    enabled: false
