# Custom values for nginx application
# This overrides the official nginx chart values

# Use official nginx chart
nginx:
  # Basic configuration
  replicaCount: 2
  
  # Deployment strategy
  deployment:
    revisionHistoryLimit: 3  # Keep only last 3 ReplicaSets
  
  # Image settings
  image:
    registry: docker.io
    repository: bitnami/nginx
    tag: "1.29.1"
  
  # Container configuration - use non-privileged port
  containerPorts:
    http: 8080  # Changed from 80 to avoid privileged port issues
  
  # Service configuration - NodePort for external access
  service:
    type: NodePort
    port: 80
    targetPort: 
      http: 8080  # Match the container port
      https: 443
    nodePort: 30080  # Specific NodePort for easy access
  
  # Resource limits
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  
  # Disable features we don't need
  ingress:
    enabled: false
  
  # Security settings
  containerSecurityContext:
    enabled: false
  
  podSecurityContext:
    enabled: false
