apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.deployment.name }}
  type: {{ .Values.service.type }}
  ports:
{{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
{{ if and (ne $.Values.service.type "ClusterIP") (hasKey . "nodePort") }}
      nodePort: {{ .nodePort }}
{{ end }}
{{- end }}
