apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: my-app
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.global.repoURL }}
    path: charts/my-app
    targetRevision: {{ .Values.global.targetRevision }}
  destination:
    server: https://kubernetes.default.svc
    namespace: my-app
  syncPolicy:
    automated:
     selfHeal: true  # Comment out for demo flexibility
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true