namespace: jenkins

pvc:
  name: jenkins-data
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  size: 20Gi

deployment:
  name: jenkins-test
  replicas: 1
  image:
    repository: jenkins-test
    tag: latest
    pullPolicy: IfNotPresent
  containerPorts:
    - name: http
      containerPort: 8080
    - name: jnlp
      containerPort: 50000
  volumeMount:
    name: jenkins-home
    mountPath: /var/jenkins_home

service:
  name: jenkins-test
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30088
    - name: jnlp
      port: 50000
      targetPort: 50000
      nodePort: 50050
